language: node_js
node_js:
  - 14
env:
  global:
   - COMMIT=${TRAVIS_COMMIT::6}

sudo: required
services:
- docker
script:
- export REPO=mayadataio/kubera-docs;
- npm ci && npm run build ;
- if [ "$TRAVIS_BRANCH" = "staging" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then export REPO=mayadataio/staging-kubera-docs;
   docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t $REPO:$TRAVIS_BRANCH-$COMMIT . && docker push $REPO:$TRAVIS_BRANCH-$COMMIT; 
  fi
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then 
   docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t $REPO:$COMMIT . && docker push $REPO;
   git clone https://${git_user}:${git_pass}@github.com/mayadata-io/kubera-docs.git; 
   cd kubera-docs;
   git checkout staging && git rebase master;
   git push https://${git_user}:${git_pass}@github.com/mayadata-io/kubera-docs.git staging;
  fi

